# This is a basic workflow to help you get started with Actions

name: 42sh CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the feature_minishell2 branch
  push:
    branches:
      - master
      - dev

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  tests:
    name: Running emile (bash tests)
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install tcsh
        run: sudo apt-get install tcsh
      - name: Compiling program
        run: make re
      # Runs a single command using the runners shell
      - name: Launch Emile s tests
        run: ./emile.sh
